version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app/client
      - ./client/public/assets:/app/public/assets
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - URI=your_url
      - JWT_SECRET=your_jwt
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/server
